- name: U_VMware_vSphere_6-7_ESXi_V1R2_STIG
  hosts: esx
  gather_facts: true
  vars:
    vmotionEnabled: []
    serviceEnabled: []
  vars_files:
    - vars/main.yml
  roles:
    - services
    - vmk
    - lockdown
    - advanced_options
    - verification
#    - debug
