- name: Disable SSH Access to ESXi Hosts in cluster
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: vcenter_password
      prompt: "Enter your vCenter Password"
      private: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: SV-239290r674799_rule Stop SSH Service
      community.vmware.vmware_host_service_manager:
        hostname: '{{ vcenter_name }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        cluster_name: '{{ cluster_name }}'
        validate_certs: no
        service_name: TSM-SSH
        state: absent
        service_policy: off
    - name: SV-239258r674703_rule Enable Lockdown Mode
      community.vmware.vmware_host_lockdown:
        cluster_name: "{{ cluster_name }}"
        hostname: "{{ vcenter_name }}"
        password: "{{ vcenter_password }}"
        username: "{{ vcenter_username }}"
        validate_certs: no
        state: present
